### ISSUE TITLE
v2: update tensor field of doc in DocumentArrayStacked

### ISSUE THREAD

**Issue by anna-charlotte** [docarray/docarray#1081] opened 2023-02-03 14:50 UTC
Not sure if this is unexpected behaviour, but we were a bit confused, so just to register this for now:
Assignment of a tensor field of a document that is part of a DocumentArray Stacked does work / not work as follows:

```python
class Image(BaseDocument):
    tensor: TorchTensor[3, 224, 224]

batch = DocumentArray[Image](
    [Image(tensor=torch.zeros(3, 224, 224)) for _ in range(10)]
)

batch = batch.stack()

# this does not work:
batch[0].tensor = torch.ones(3, 224, 224) 

# this works:
batch[0].tensor[:] = torch.ones(3, 224, 224) 
# this works too
batch.tensor[0] = torch.ones(3, 224, 224) 

```
So maybe let's document this behaviour or fix if unexpected.

**Comment by JohannesMessner** [comment] 2023-02-08 10:44
I would definitely not call this expected. Ideally all 3 would work imo, and I thought the first one would be covered by our setitem. So bug I would say? @samsja @JoanFM what do you think?

**Comment by JoanFM** [comment] 2023-02-08 10:49
I am not so sure, I will check, but the fact that it successfully executes may not be actually working.

When u do `batch[0]` and assign a tensor (should this be restacked)?

**Comment by JohannesMessner** [comment] 2023-02-08 10:52
> When u do batch[0] and assign a tensor (should this be restacked)?
it should just do an assignment in the big stacked tensor imo. The Document returned by `batch[0]` should as its `.tensor` hold a view into the big stacked tensor (I think it already does), and the assignment should assign back into that tensor.
That is also how views in pure pytorch work, right?

**Comment by samsja** [comment] 2023-02-08 10:53
> When u do batch[0] and assign a tensor (should this be restacked)?

no need to restacked you can just write in the good piece of memory with the view


It is not a bug IMO as it is expecting to behave like this. We just change the reference on the tensor field to smth new, this is what document do.
But this can be "fix" or at least we can change the behavior with a `__setitiem__` trick or a pydantic validation. I am planning in taking a look at these when I have time

**Comment by JoanFM** [comment] 2023-02-08 10:54
then what happens if I reassign and then I iterate over `documents`? do I get the tensor from the underlying unstacked or I rebuild from the `view` as well?

**Comment by JohannesMessner** [comment] 2023-02-08 10:57
>It is not a bug IMO as it is expecting to behave like this.

yes from a low-level technical POV it is expected, but not sure if it is the user experience that we want.

I see two options/stories:

- "`batch[0]` is a completely normal Document that happens to hold a view into a bigger tensor as its `.tensor` field. It is not tied to anything. if you re-assign that field, of course you just assign a new tensor and nothing else happens"
- "`batch[0]` is a view into `batch`. They are tied together in the same way `tensor[0]` is tied to `tensor` in pytorch. So if you re-assign in one place, you re-assign everywhere"

BTW @anna-charlotte , what exactly does "does not work" mean for the first example?

**Comment by samsja** [comment] 2023-03-13 10:05
Fixed in https://github.com/docarray/docarray/pull/1183

**Closed by samsja** 2023-03-13 10:05 UTC
