### ISSUE TITLE
docs: add documentation on FastAPI swagger UI with BaseDoc

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1558] opened 2023-05-22 07:00 UTC
# Context

We want to add documentation on how to create a fast API app with DocArray and get a swagger UI with a BaseDoc

**Comment by shivance** [comment] 2023-05-23 18:25
Hi @samsja I would like to contribute for this issue. Please assign me.

**Comment by JoanFM** [comment] 2023-05-31 09:19
hey @shivance , any progress on this matter?

**Comment by shivance** [comment] 2023-05-31 09:24
For this one I've been waiting for @samsja to update on contrib guideline updation

**Comment by JoanFM** [comment] 2023-05-31 09:26
This has been updated thanks to #1547

**Comment by shivance** [comment] 2023-05-31 09:27
Cool I'll start working on it then

**Comment by shivance** [comment] 2023-06-03 08:13
Sorry, I've got a bit busy lately, it would be delayed at my end. Unassigning myself to avoid this issue going in backlog.

Thanks @JoanFM !

**Comment by munish0838** [comment] 2023-10-22 17:16
Hi, is this issue fixed or needs contribution yet. 
Would like to contribute

**Comment by JoanFM** [comment] 2023-12-06 10:55
We want to show how to leverage DocArray to be used with FastAPI and to get rich SwaggerUI documentation about the endpoints, the examples, etc ...

**Comment by AkhilYadavPadala** [comment] 2023-12-06 11:03
Could you assign this issue? @JoanFM

**Comment by AkhilYadavPadala** [comment] 2023-12-06 12:54
How do I get the code @JoanFM 
I think the issue is closed or deleted
#1558 Doesn't clickable

**Comment by JoanFM** [comment] 2023-12-06 18:02
There is no specific code.

**Comment by AkhilYadavPadala** [comment] 2023-12-06 18:09
Could you elaborate on this issue further?
I'm a little bit confused

**Comment by JoanFM** [comment] 2023-12-06 18:11
There is Documentation missing about this usage with FastAPI. There is no specific code, you can try develop a FastAPI app using docarray as Pydantic models. If you do not know about FastAPI it may not be the most suitable ticket to take.

**Comment by AkhilYadavPadala** [comment] 2023-12-06 18:14
Are there any sources to learn FastAPI
I'll do it by learning if it's possible @JoanFM

**Comment by ai-naymul** [comment] 2024-01-14 17:00
@JoanFM @samsja 
I have seen that this issue has not been solved for a long time. I have a proposal regarding this and would love to contribute.

Here is my approach:

Step 1: Define My Schemas
First, I need to define my input and/or output documents using the BaseDoc class from DocArray.

Step 2: Use documents with FastAPI

After creating my schemas, I can use my documents with FastAPI.

Step 3: Specify Tensor Shapes

DocArray allows me to specify and validate the shapes of tensors. I can do this by specifying the expected shape in the type hint of my document.

Step 4: Start the FastAPI App

I can start the FastAPI app after that This will start the app and provide you with a Swagger UI that you can access by navigating to http://127.0.0.1:8000/docs in my web browser.

That's it! I now have a FastAPI app with DocArray and a Swagger UI.

**Comment by JoanFM** [comment] 2024-01-14 19:57
> @JoanFM @samsja I have seen that this issue has not been solved for a long time. I have a proposal regarding this and would love to contribute.
> 
> Here is my approach:
> 
> Step 1: Define My Schemas First, I need to define my input and/or output documents using the BaseDoc class from DocArray.
> 
> Step 2: Use documents with FastAPI
> 
> After creating my schemas, I can use my documents with FastAPI.
> 
> Step 3: Specify Tensor Shapes
> 
> DocArray allows me to specify and validate the shapes of tensors. I can do this by specifying the expected shape in the type hint of my document.
> 
> Step 4: Start the FastAPI App
> 
> I can start the FastAPI app after that This will start the app and provide you with a Swagger UI that you can access by navigating to localhost in my web browser.
> 
> That's it! I now have a FastAPI app with DocArray and a Swagger UI.

makes sense

**Comment by ai-naymul** [comment] 2024-01-15 17:17
> > @JoanFM @samsja I have seen that this issue has not been solved for a long time. I have a proposal regarding this and would love to contribute.
> > Here is my approach:
> > Step 1: Define My Schemas First, I need to define my input and/or output documents using the BaseDoc class from DocArray.
> > Step 2: Use documents with FastAPI
> > After creating my schemas, I can use my documents with FastAPI.
> > Step 3: Specify Tensor Shapes
> > DocArray allows me to specify and validate the shapes of tensors. I can do this by specifying the expected shape in the type hint of my document.
> > Step 4: Start the FastAPI App
> > I can start the FastAPI app after that This will start the app and provide you with a Swagger UI that you can access by navigating to localhost in my web browser.
> > That's it! I now have a FastAPI app with DocArray and a Swagger UI.
> 
> makes sense

Hi @JoanFM,
Where to push the changes in which path?

**Comment by ai-naymul** [comment] 2024-01-15 17:22
> > > @JoanFM @samsja I have seen that this issue has not been solved for a long time. I have a proposal regarding this and would love to contribute.
> > > Here is my approach:
> > > Step 1: Define My Schemas First, I need to define my input and/or output documents using the BaseDoc class from DocArray.
> > > Step 2: Use documents with FastAPI
> > > After creating my schemas, I can use my documents with FastAPI.
> > > Step 3: Specify Tensor Shapes
> > > DocArray allows me to specify and validate the shapes of tensors. I can do this by specifying the expected shape in the type hint of my document.
> > > Step 4: Start the FastAPI App
> > > I can start the FastAPI app after that This will start the app and provide you with a Swagger UI that you can access by navigating to localhost in my web browser.
> > > That's it! I now have a FastAPI app with DocArray and a Swagger UI.
> > 
> > 
> > makes sense
> 
> Hi @JoanFM, Where to push the changes in which path?

after the send over fastapi section or in the fastapi section?

![lol](https://github.com/docarray/docarray/assets/68547750/bc5ef83f-31f0-4937-936c-0647c92594e6)

**Comment by JoanFM** [comment] 2024-01-15 17:24
Inside the FastAPI section I'd suggest

**Comment by ai-naymul** [comment] 2024-01-15 17:26
> Inside the FastAPI section I'd suggest

What we want add I think it's already there
Could you please recheck?

![Screenshot_3](https://github.com/docarray/docarray/assets/68547750/0fbf871f-ff09-486c-ad68-17bf1bcfa23b)

**Comment by ai-naymul** [comment] 2024-01-15 17:54
> Inside the FastAPI section I'd suggest

I think Swagger UI documentation is already there, could you please recheck that one?

[https://docs.docarray.org/user_guide/sending/api/fastAPI/](Send Over FastAPI)

**Comment by ai-naymul** [comment] 2024-01-17 04:40
@JoanFM @samsja

**Comment by JoanFM** [comment] 2024-01-17 07:31
true, closingg

**Closed by JoanFM** 2024-01-17 07:31 UTC
Labels: good-first-issue
