### ISSUE TITLE
Weaviate Minimum example failing

### ISSUE THREAD

**Issue by ghpkishore** [docarray/docarray#433] opened 2022-07-08 13:51 UTC
Hi in your documentation: https://docarray.jina.ai/advanced/document-store/weaviate/#minimum-example for some reason, when i run using debug mode, it works perfectly, but fails when i run it all at once it fails. 

I am using Macbook pro m1 chip.

I installed all the required packages as well as given in the example.

This is my code:
```python
from docarray import DocumentArray
from transformers import AutoModel, AutoTokenizer

da = DocumentArray(
    storage="weaviate", config={"name": "Persisted", "host": "localhost", "port": 8080}
)

from docarray import Document

da.extend(
    [
        Document(text='Persist Documents with Weaviate.'),
        Document(text='And enjoy fast nearest neighbor search.'),
        Document(text='All while using DocArray API.'),
    ]
)


tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
model = AutoModel.from_pretrained('bert-base-uncased')



def collate_fn(da):
    return tokenizer(da.texts, return_tensors='pt', truncation=True, padding=True)


da.embed(model, collate_fn=collate_fn)



results = da.find(
    DocumentArray([Document(text='How to persist Documents')]).embed(
        model, collate_fn=collate_fn
    ),
    limit=1,
)


print(results[0].texts)
``` 

Output:

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/docarray/array/mixins/embed.py:96: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  batch_inputs[k] = torch.tensor(v, device=device)
['Persist Documents with Weaviate.']
Exception ignored in: <function BaseGetSetDelMixin.__del__ at 0x11e743370>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/docarray/array/storage/base/getsetdel.py", line 290, in __del__
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/docarray/array/storage/weaviate/getsetdel.py", line 79, in _save_offset2ids
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/docarray/array/storage/weaviate/backend.py", line 226, in _update_offset2ids_meta
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/weaviate/data/crud_data.py", line 124, in create
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/weaviate/connect/connection.py", line 314, in post
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 590, in post
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 532, in request
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 711, in merge_environment_settings
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/utils.py", line 797, in get_environ_proxies
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/utils.py", line 781, in should_bypass_proxies
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 2649, in proxy_bypass
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 2626, in proxy_bypass_macosx_sysconf
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 2568, in _proxy_bypass_macosx_sysconf
ImportError: sys.meta_path is None, Python is likely shutting down

**Comment by JoanFM** [comment] 2022-07-08 14:02
Hey @ghpkishore ,

What is your `transformers` version? Are you sure it fullfills docarray requirements? 'transformers>=4.16.2'

**Comment by JoanFM** [comment] 2022-07-09 07:59
Hey @ghpkishore, I do not reproduce the error. Have you checked your `weaviate-client` version? As per the error with the `plural` we are fixing the example in #437

**Comment by ghpkishore** [comment] 2022-07-11 05:37
https://github.com/SeleniumHQ/selenium/pull/3263 This seems to be related to the error?  you can look at this as well. Cause I am using the latest version of the weaviate client as well. https://stackoverflow.com/questions/67902926/python-importerror-in-del-how-to-solve-this.

**Comment by JoanFM** [comment] 2022-07-11 06:28
I do not understand this last message and how is it related to the original bug report

**Comment by ghpkishore** [comment] 2022-07-15 05:19
I tried to find the cause of failure but wasn’t able to.  The last comment was my attempt to try to solve the error which was being thrown in the original comment.  Don’t think I have the ability to solve it by myself.  If you are not able to replicate this error you can close the issue.

**Comment by JoanFM** [comment] 2022-07-15 08:25
@ghpkishore,

what do u mean in the original message about `DEBUG` mode?

**Comment by ghpkishore** [comment] 2022-07-15 08:55
by `DEBUG` mode, i meant instead of using python run button in VScode, i used python debug button. 

Regarding `__del__`, I am not sure. I couldn't figure out whether the error was in `save_offset_ids` or in `BaseGetSetDelMixin`, that's why my second comment in this post is edited.

**Comment by JoanFM** [comment] 2022-07-15 09:30
save offset ids is calling in the delete, u can add prints to see who is there

**Comment by JoanFM** [comment] 2022-07-15 11:01
In order to help debugging, can you tr:

```python
from docarray import DocumentArray
from transformers import AutoModel, AutoTokenizer

da = DocumentArray(
    storage="weaviate", config={"name": "Persisted", "host": "localhost", "port": 8080}
)

from docarray import Document

da.extend(
    [
        Document(text='Persist Documents with Weaviate.'),
        Document(text='And enjoy fast nearest neighbor search.'),
        Document(text='All while using DocArray API.'),
    ]
)


tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
model = AutoModel.from_pretrained('bert-base-uncased')



def collate_fn(da):
    return tokenizer(da.texts, return_tensors='pt', truncation=True, padding=True)


da.embed(model, collate_fn=collate_fn)



results = da.find(
    DocumentArray([Document(text='How to persist Documents')]).embed(
        model, collate_fn=collate_fn
    ),
    limit=1,
)


print(results[0].texts)

da.save_offset_ids()
```

**Comment by JoanFM** [comment] 2022-08-04 08:22
Hello @ghpkishore ,

Any news about this?

**Comment by ghpkishore** [comment] 2022-08-04 08:39
Hi,

Apologies for not replying sooner.
I tried with this and couldn’t figure out the error. Didn’t know if it was
with jina or weavite or hugging face or if it is that apple m1 chip has a
problem. I left the problem for it was out of my capability to figure it
out.

Regards
Kishore

**Comment by JoanFM** [comment] 2022-08-04 09:06
Did u try what I proposed?

**Comment by JoanFM** [comment] 2022-08-13 04:00
It seems to come from weaviate client. I think you should try to open an issue on their side.

**Comment by bobvanluijt** [comment] 2022-08-13 22:39
Will be solved with this PR: https://github.com/jina-ai/docarray/pull/487

**Comment by JoanFM** [comment] 2022-10-03 14:27
Hey @bobvanluijt , any news on the progress on this?

**Comment by bobvanluijt** [comment] 2022-10-04 12:00
Hi @JoanFM – thanks for the nudge. You can close this issue already, it is part of the PR, which itself is still being worked on.

**Comment by Jackmin801** [comment] 2022-10-11 08:20
I think this is related to https://github.com/jina-ai/docarray/pull/604

Should try this again after that PR merges

**Comment by Jackmin801** [comment] 2022-10-11 08:25
@bobvanluijt Oh btw. You might want to look at the tests added in that PR.
I had to skip Weaviate because DocArrays backed by Weaviate seem to either have a cyclical reference or registers itself to a module resulting in the DocArray being created with a refcount of 2 instead of 1.
I'll look into it but just thought you might want to be aware since you know this part of the code best.

**Comment by bobvanluijt** [comment] 2022-10-12 18:11
Thanks @Jackmin801 – we are aware of this. Appreciate the feedback 🙏

**Comment by JoanFM** [comment] 2022-12-01 08:12
Hey @bobvanluijt ,

Has this been solved by the newest version upgrade?

**Comment by bobvanluijt** [comment] 2022-12-02 15:10
Looping in @dirkkul – can you help with @JoanFM's question, please?

**Closed** 2023-04-21 11:08 UTC
