### ISSUE TITLE
Missing json methods for DocList and DocVec

### ISSUE THREAD

**Issue by movchan74** [docarray/docarray#1491] opened 2023-05-04 17:26 UTC
#### Description:
`DocList` and `DocVec` do not have their own `json` methods, which could improve usability and provide more convenient serialization.

#### Suggested feature:

Implement `json` methods for `DocList` and `DocVec` to allow users to directly serialize these objects. This would enhance the user experience and provide a more consistent interface for working with `DocList` and `DocVec` instances.

**Comment by JoanFM** [comment] 2023-05-04 22:50
For DocVec we do not have, but for DocList we have `to_json`; is that good enough?

As per the DocVec thing, we have an issue to add in #1330

**Comment by samsja** [comment] 2023-05-05 08:15
> but it would be nice to have the same interface for Docs, DocLists and DocVecs.

@movchan74 Good point. DocVec will have the same interface as DocList when we will support all of the methods there. For now we only support Protobuf but we json is coming asap.

**Comment by samsja** [comment] 2023-05-08 11:45
fyi @movchan74 in today released (0.31.0) we added an alias `to_json` to `BaseDoc` to have a similar experience. We will enforce this as much as we can for new and existing method

**Comment by JoanFM** [comment] 2023-05-19 11:09
Closing as duplicate of #1330

**Closed by JoanFM** 2023-05-19 11:09 UTC
