### ISSUE TITLE
Bottleneck on update offset2ids operation

### ISSUE THREAD

**Issue by alphinside** [docarray/docarray#700] opened 2022-10-27 09:09 UTC
I have a docarray collection  of 2 million rows and using ES backend and I notice that any sync operation take a very long time. After inspecting the code, this is caused by the upsert operation on function `_update_offset2ids_meta` which iterate all existing offsets and upsert them all to ES -> on my system it takes around 13-15s for docarray of length 150k. I try to find a way to optimize this but haven't found any other way except maybe trying to query all of the indexed offset first and then compare it to `self._offset2ids.ids` then only upsert the changed offset. It will be more optimize to update only the updated offsets

In addition, in my case, having offset2ids is not really helpful and become significant operational overhead ( in term of service throughput and memory consumption ), so having option to disable offset information will be helpful

**Comment by JoanFM** [comment] 2022-10-27 09:11
I think we can do 2 things. Work on #542 or trying to optimize knowing which offsets need to be updated

**Comment by alphinside** [comment] 2022-10-29 23:49
Update on this, now I even cannot instantiate the docarray object as on the `__init__storage` function call it always timeout when trying to get all ids from offset ES index. It will be appreciated if you guys can help with this

**Comment by samsja** [comment] 2022-11-04 14:28
closing this issue as the problem is beeing tracked in  https://github.com/docarray/docarray/issues/542 and in PR is in progress https://github.com/docarray/docarray/pull/718

**Closed by samsja** 2022-11-04 14:28 UTC
